# Generated by Django 3.0.6 on 2020-05-27 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userlist_id1', models.CharField(max_length=100)),
                ('userlist_id2', models.CharField(max_length=100)),
                ('chat_id', models.CharField(default=uuid.uuid4, max_length=100)),
            ],
        ),
    ]
