# Generated by Django 3.0.6 on 2020-05-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat_id',
            field=models.CharField(max_length=200),
        ),
    ]
