# Generated by Django 3.0.6 on 2020-06-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_adduser_roomchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='documents',
            field=models.FileField(default='documents/', upload_to=''),
        ),
    ]
