# Generated by Django 3.0.6 on 2020-06-21 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200621_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='private_chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='room_chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.RoomChat'),
            preserve_default=False,
        ),
    ]
