# Generated by Django 3.0.6 on 2020-06-21 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200621_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='room_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.RoomChat'),
        ),
    ]
