# Generated by Django 3.0.6 on 2020-06-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200621_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='display_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
