# Generated by Django 3.0.6 on 2020-06-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_userlist_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchat',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
