# Generated by Django 3.0.6 on 2020-06-24 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20200622_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
