# Generated by Django 3.0.6 on 2020-06-24 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20200624_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
