# Generated by Django 3.0.6 on 2020-07-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20200624_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchat',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
