# Generated by Django 3.0.6 on 2020-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_roomchat_new_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
