# Generated by Django 3.0.6 on 2020-07-05 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='private_chat',
        ),
        migrations.AlterField(
            model_name='notification',
            name='room_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='chat.RoomChat'),
        ),
        migrations.CreateModel(
            name='NotificationPrivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.UserList')),
                ('private_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Chat')),
            ],
        ),
    ]
