# Generated by Django 3.0.6 on 2020-07-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20200705_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationprivate',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
