# Generated by Django 3.0.6 on 2020-07-05 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0019_notificationprivate_new_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationprivate',
            name='add_user',
        ),
        migrations.RemoveField(
            model_name='notificationprivate',
            name='private_chat',
        ),
        migrations.AddField(
            model_name='notificationprivate',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationprivate',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.UserList'),
        ),
    ]
